In [1]:
import numpy as np

# creating a array using numpy

In [3]:
food = np.array(['pakora', 'samosa', 'raita'])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [5]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [8]:
type(food)

numpy.ndarray

In [7]:
type(price)

numpy.ndarray

In [9]:
len(price)

3

In [10]:
len(food)

3

In [13]:
price[0:]

array([5, 5, 5])

In [15]:
food[1]

'samosa'

In [16]:
price.mean()

5.0

In [18]:
# zeros

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# table
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
# line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [34]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [36]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [38]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [40]:
b = np.array([10.2, 3.4, 53.6, 91.6, 45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [41]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [42]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D arrays

In [49]:
a = np.array([[1,2,3,4,5], [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [50]:
b = np.array([[6,7], [8,9]])
b

array([[6, 7],
       [8, 9]])

In [51]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 4, 3, 2, 1, 8, 9]])